# ...existing code...
<head>
    # ...existing code...
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
</head>
<body>
    # ...existing code...
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="{{ asset('js/swiper-config.js') }}"></script>
</body>
# ...existing code...
